-- Create EMP table
CREATE OR alter TABLE SCH_DEMO.EMP (
    EMP_ID INT AUTOINCREMENT PRIMARY KEY,
    EMP_NAME STRING,
    DEPT STRING,
    SALARY NUMBER(10,2),
    JOIN_DATE DATE
);

EXECUTE IMMEDIATE FROM './emp_tbl_records_insert.sql';